### ISSUE TITLE
Sample Application

### ISSUE THREAD

**Issue by fahimshahrierrasel** [jrvansuita/SQLiteParser#1]
# Sample Application / Demo Application

Please try to make a sample application by using your tools.
It will be very helpful for the beginner like me. 

Thank you

**Comment by jrvansuita** [comment]
Sure @fahimshahrierrasel, I will do that.

**Comment by jrvansuita** [comment]
@fahimshahrierrasel you can take a look at this repo: https://github.com/jrvansuita/SQLiteHelper
