### ISSUE TITLE
Jcenter integration

### ISSUE THREAD

**Issue by Nikhil-z** [jrvansuita/SQLiteParser#2]
First of all thanks for your effort . it will be less painful if you add your lib to Jcenter  . Hope you will add soon

**Comment by jrvansuita** [comment]
Of course, I will check the possibility.

**Comment by jrvansuita** [comment]
@Nikhil-z Can you help me?

I'm trying to make a jitpack integration to simple import this github repository on gradle.

Jitpack docs are telling me to use this, on gradle:

```
    allprojects {
		repositories {
			...
			maven { url "https://jitpack.io" }
		}
	}
```

and

  ```
  dependencies {
	        compile 'com.github.jrvansuita:SQLiteParser:master-0.0.1'
	}
```

Ok, the sync it's working, but my classes aren't showing up when I try to use them.

**Comment by Xstar97** [comment]
May I suggest using bintray?
You can create your own repository in bintray & link any of your libraries to jcenter very easily....I also had a ton of trouble when releasing my first library...this is the tutorial that I used https://inthecheesefactory.com/blog/how-to-upload-library-to-jcenter-maven-central-as-dependency/en

If you have any questions, feel free to ask

**Comment by Xstar97** [comment]
When creating a sample...it's usually better to use
compile library(':FreemiumLibrary')

compile project(':FreemiumLibrary')

Also make sure the methods are public too.

**Comment by Xstar97** [comment]
This is my first ever library ever released which you can use as a reference too if you are going try my suggestion... checkout the build.gradles project, app, & library for some pointers...https://github.com/Xstar97/easySocial

**Comment by jrvansuita** [comment]
@Xstar97 I want to use jitpack because it's free. I already checked bintray and created a trial acc, but I have to pay after the trial. I don't have conditions to pay to publish a library.

**Comment by Xstar97** [comment]
You have to pick the open source plan, it's completely free

**Comment by Nikhil-z** [comment]
@jrvansuita  Hi , Let me check ASAP .  Always Happy to help :)

**Comment by Nikhil-z** [comment]
@jrvansuita  . Can you tell what package name you used for your library and also it will be fare to use some other name instead of **Sql** for that class   .

**Comment by jrvansuita** [comment]
@Nikhil-z What class name do you suggest? I created those classes inside an app project, so the package doesn't matter. I can change the package to com.vansuita.sqlparser, what do you think?

**Comment by jrvansuita** [comment]
@Xstar97 I was taking a look on the "inthecheesefactor" tutorial. It's such harder to publish the project on maven or jcenter. I really want to get thinks working with jitpack, it's more simple.

**Comment by Nikhil-z** [comment]
@jrvansuita Jitpack is much simple and easy to use compare to others .Just have a look at this [http://zserge.com/blog/jitpack.html](url)

**Comment by jrvansuita** [comment]
@Nikhil-z  I'm getting 404 on  http://zserge.com/blog/jitpack.html

**Comment by jrvansuita** [comment]
Ok @Nikhil-z  and @Xstar97  I did it. I created a new repository with this library. Take a look, now we have 2 line of dependencies and we are good to go.    https://github.com/jrvansuita/SQLiteHelper

**Comment by Nikhil-z** [comment]
Great job brother :)
